/** basic: ADVERTISE, ANALYZE, CREATE_CONTENT, MESSAGING, MODERATE, VIEW_MONETIZATION_INSIGHTS */
export const BASIC_ROLES = [
  "ADVERTISE",
  "ANALYZE",
  "CREATE_CONTENT",
  "MESSAGING",
  "MODERATE",
  "VIEW_MONETIZATION_INSIGHTS",
]

/** full: basic + MANAGE */
export const FULL_ROLES = [
  "ADVERTISE",
  "ANALYZE",
  "CREATE_CONTENT",
  "MESSAGING",
  "MODERATE",
  "MANAGE",
  "VIEW_MONETIZATION_INSIGHTS",
]

export function getRolesByMode(mode: "basic" | "full"): string[] {
  return mode === "full" ? FULL_ROLES : BASIC_ROLES
}

export const BASIC_LABEL =
  "Basic: ADVERTISE, ANALYZE, CREATE_CONTENT, MESSAGING, MODERATE, VIEW_MONETIZATION_INSIGHTS"
export const FULL_LABEL =
  "Full: MANAGE, ADVERTISE, ANALYZE, CREATE_CONTENT, MESSAGING, MODERATE, VIEW_MONETIZATION_INSIGHTS"
